### PR TITLE
Update Japanese Localizable.xcstrings

### PR DESCRIPTION
**Pull request by konnano**

### CODE REVIEW

**Comment by milanvarady** [comment]
Thanks for the translation. I'll merge this pr before the next release so you can fix potential problems until then.

**Comment by konnano** [comment]
Thank you for your review. I would like to be able to translate the following sentences as well.

Error. Broken brew path, or damaged installation. Check brew path in settings, or try reinstalling Homebrew (Manage Homebrew->Reinstall)

**Comment by konnano** [comment]
The translation is finished
Very interesting app.

**Review by milanvarady — APPROVED** [review]
Will be included in the new release, hopefully soon 🤞

**Pull request merged**
